### ISSUE TITLE
Crash when dragging buttons and input field

### ISSUE THREAD

**Issue by plaidcodes** [Ameobea/svelte-todo#1]
Firefox 95.0.2 (64-bit), Windows. Via demo site https://sveltekit-todo.ameo.dev/

You can drag the [+] button, cancel, submit, and the input field by grabbing their edges. If you do, the app produces an error and stops functioning.

> Uncaught (in promise) Error: missing 'id' property for item { "isDndShadowItem": true }

**Comment by Ameobea** [comment]
You're right, I hadn't noticed that.

I worked around it by disabling dragging of the todos when the `AddTodo` button is clicked and re-enabling when the mouse is released.
